// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: ask.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AskService_Ask_FullMethodName = "/rag.ask.v1.AskService/Ask"
)

// AskServiceClient is the client API for AskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AskServiceClient interface {
	Ask(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (*AskResponse, error)
}

type askServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAskServiceClient(cc grpc.ClientConnInterface) AskServiceClient {
	return &askServiceClient{cc}
}

func (c *askServiceClient) Ask(ctx context.Context, in *AskRequest, opts ...grpc.CallOption) (*AskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AskResponse)
	err := c.cc.Invoke(ctx, AskService_Ask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AskServiceServer is the server API for AskService service.
// All implementations must embed UnimplementedAskServiceServer
// for forward compatibility.
type AskServiceServer interface {
	Ask(context.Context, *AskRequest) (*AskResponse, error)
	mustEmbedUnimplementedAskServiceServer()
}

// UnimplementedAskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAskServiceServer struct{}

func (UnimplementedAskServiceServer) Ask(context.Context, *AskRequest) (*AskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ask not implemented")
}
func (UnimplementedAskServiceServer) mustEmbedUnimplementedAskServiceServer() {}
func (UnimplementedAskServiceServer) testEmbeddedByValue()                    {}

// UnsafeAskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AskServiceServer will
// result in compilation errors.
type UnsafeAskServiceServer interface {
	mustEmbedUnimplementedAskServiceServer()
}

func RegisterAskServiceServer(s grpc.ServiceRegistrar, srv AskServiceServer) {
	// If the following call pancis, it indicates UnimplementedAskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AskService_ServiceDesc, srv)
}

func _AskService_Ask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AskServiceServer).Ask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AskService_Ask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AskServiceServer).Ask(ctx, req.(*AskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AskService_ServiceDesc is the grpc.ServiceDesc for AskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rag.ask.v1.AskService",
	HandlerType: (*AskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ask",
			Handler:    _AskService_Ask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ask.proto",
}
